baseURL = 'https://zhuaoyuan.github.io/my/'
languageCode = 'zh-cn'
title = "zay's game of life"
theme = 'paper'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[security]
  enableInlineShortcodes = true
  
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[params]
  color = 'linen'
  github = 'zhuaoyuan'
  avatar = 'http://localhost:1313/my/images/avatar.png'
  name = 'zhuaoyuan'
  bio = '牢骚太盛防肠断'

[services]
  [services.disqus]
    shortname = 'zhuaoyuan'
